import { themeTokens } from './src/theme/colors.js'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-dim': '#d9dadb',
        'surface-glass': 'rgba(255, 255, 255, 0.7)',
        'border-subtle': '#ECEFF1',
        background: 'rgb(var(--color-background) / <alpha-value>)',
        surface: 'rgb(var(--color-surface) / <alpha-value>)',
        'surface-2': 'rgb(var(--color-surface-2) / <alpha-value>)',
        'surface-3': 'rgb(var(--color-surface-3) / <alpha-value>)',
        border: 'rgb(var(--color-border) / <alpha-value>)',
        text: 'rgb(var(--color-text) / <alpha-value>)',
        muted: 'rgb(var(--color-muted) / <alpha-value>)',
        primary: 'rgb(var(--color-primary) / <alpha-value>)',
        'primary-soft': 'rgb(var(--color-primary-soft) / <alpha-value>)',
        'on-primary': 'rgb(var(--color-on-primary) / <alpha-value>)',
        secondary: 'rgb(var(--color-secondary) / <alpha-value>)',
        tertiary: 'rgb(var(--color-tertiary) / <alpha-value>)',
        danger: 'rgb(var(--color-danger) / <alpha-value>)',
        warning: 'rgb(var(--color-warning) / <alpha-value>)',
        success: 'rgb(var(--color-success) / <alpha-value>)',
        navy: 'rgb(var(--color-navy) / <alpha-value>)',
        glass: 'rgb(var(--color-glass) / <alpha-value>)',
        'navy-deep': '#001A43',
        'primary-container': '#d32f2f',
        'primary-fixed': '#ffdad6',
        'primary-fixed-dim': '#ffb3ac',
        'on-primary-container': '#fff2f0',
        'on-primary-fixed': '#410003',
        'on-primary-fixed-variant': '#930010',
        'secondary-container': '#d7e4ec',
        'secondary-fixed': '#d7e4ec',
        'secondary-fixed-dim': '#bbc8d0',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#5a666d',
        'on-secondary-fixed': '#111d23',
        'on-secondary-fixed-variant': '#3c494f',
        'tertiary-container': '#b05700',
        'tertiary-fixed': '#ffdcc6',
        'tertiary-fixed-dim': '#ffb786',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fff2eb',
        'on-tertiary-fixed': '#311300',
        'on-tertiary-fixed-variant': '#723600',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        outline: '#8f6f6c',
        'outline-variant': '#e4beba',
        'on-surface': '#191c1d',
        'on-surface-variant': '#5b403d',
        'on-background': '#191c1d',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'inverse-primary': '#ffb3ac',
      },
      boxShadow: {
        soft: '0 18px 50px rgba(15, 23, 42, 0.08)',
        glow: '0 0 0 1px rgba(175, 16, 26, 0.12), 0 24px 80px rgba(175, 16, 26, 0.12)',
      },
      backgroundImage: {
        'brand-radial':
          'radial-gradient(circle at top left, rgba(var(--color-primary) / 0.13), transparent 35%), radial-gradient(circle at top right, rgba(var(--color-tertiary) / 0.12), transparent 28%), linear-gradient(180deg, rgba(var(--color-surface) / 0.96), rgba(var(--color-background) / 1))',
      },
      screens: {
        '3xl': '1800px',
      },
      fontFamily: {
        inter: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
  safelist: [
    ...Object.keys(themeTokens.atelier),
    'bg-primary/10',
    'bg-primary/15',
    'bg-primary/20',
    'bg-secondary/10',
    'bg-tertiary/10',
    'text-primary',
    'text-secondary',
    'text-tertiary',
    'text-muted',
  ],
}
